### ISSUE TITLE
Install and import

### ISSUE THREAD

**Issue by Yuxin-Cui** [YangLabHKUST/Portal#2]
Dear there, 

I have tried to test it, but was stuck at the import step. After run `import portal` under Jupyter lab. The following error message developed:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [15], in <cell line: 1>()
----> 1 import portal

File C:\jlab_server\lib\site-packages\portal\__init__.py:3, in <module>
      1 from __future__ import absolute_import
----> 3 from .api import API, APIException
      4 from ._version import __version__
      6 __all__ = ['API', 'APIException']

File C:\jlab_server\lib\site-packages\portal\api.py:4, in <module>
      1 #!/usr/bin/env python
      2 from functools import wraps
----> 4 import cookielib
      5 import HTMLParser
      6 import json

ModuleNotFoundError: No module named 'cookielib'

I hav tried to fix it, by running:

import http.cookiejar
cookielib = http.cookiejar

But this issue remains the same. 

I wonder whether you could help to fix it. 

Thanks

**Comment by jiazhao97** [comment]
Hi there,

Thank you for your interest in our Portal package! 

I wonder did you install our package with the command `pip install portal`? If so, the package you installed is [https://github.com/jlopez/portal](https://github.com/jlopez/portal), instead of ours. If you want to try our package, please follow [https://github.com/YangLabHKUST/Portal#installation](https://github.com/YangLabHKUST/Portal#installation) to install our package.

Best,
Jia

**Comment by Yuxin-Cui** [comment]
Thanks! I tried again using pip install portal-sc. The error message was:
![image](https://user-images.githubusercontent.com/62621276/177030655-1d0e2571-eaff-44b8-ba93-6cbc649fa246.png)

**Comment by jiazhao97** [comment]
This error occurred during installing `louvain` package. The reason may be that `setuptools>=58` does not support `use_2to3` (see [this link](https://stackoverflow.com/questions/69100275/error-while-downloading-the-requirements-using-pip-install-setup-command-use-2)). Can you try `pip install setuptools==57.5.0`?  Alternatively, you can try the following command to install Portal package:
```bash
git clone https://github.com/YangLabHKUST/Portal.git
cd Portal
conda env update --f environment.yml
conda activate portal
```
