### ISSUE TITLE
confusion about fig.3c

### ISSUE THREAD

**Issue by yuxiaokang-source** [YangLabHKUST/Portal#3]
Great work! I have some confusion about the fig3c,
<img width="252" alt="image" src="https://user-images.githubusercontent.com/59059267/208245665-96fcacbd-4d3f-41fd-ad4b-1084f110d50d.png">
from 10x-annotations , there are 9 neuron subpopulations
<img width="474" alt="image" src="https://user-images.githubusercontent.com/59059267/208245715-6dbba514-28df-4b2d-abdf-b7d0c1cc567e.png">
but fig3c only show 8 dot ,why it is inconsistent? or how to understand this dot plot of upper pannel, middle pannel and bottom panel?

**Comment by gefeiwang** [comment]
Hi there,

Thank you for your interest! There are 38 neuron subpopulations in the 10x annotation in Fig. 3c (8 in the first row, 23 in the second row and 7 in the last row). We only annotated larger clusters in Fig. 3a.
