### ISSUE TITLE
How to improve same-cell scRNA/scATAC-seq integration results?

### ISSUE THREAD

**Issue by yuyingrong** [YangLabHKUST/Portal#6]
Greetings developers!

We are using Portal for single-cell same-cell RNA/ATAC-seq integration. However, the output UMAP clusters seem not sufficiently integrated (cells from either assay do not overlap). 
<img width="691" alt="image" src="https://user-images.githubusercontent.com/50842845/226654442-e4d122c7-0887-4513-b156-d8e2204c449f.png">

Our test data: https://www.10xgenomics.com/resources/datasets/pbmc-from-a-healthy-donor-granulocytes-removed-through-cell-sorting-10-k-1-standard-2-0-0. 

For RNA assay, we filtered the cells using Seurat (no normalization applied), and extracted the raw count matrix as an input for Portal. 

For ATAC assay, we used ArchR to filter the cells and generate a raw count matrix (GeneScoreMatrix: https://www.archrproject.com/bookdown/calculating-gene-scores-in-archr.html).

Our final input included 10338 cells from the RNA assay and 9939 cells from the ATAC assay, where 9213 cell barcodes intersected. Portal identified 4000 highly variable genes in each assay, of which 267 intersected. 

We followed the multiomic integration protocol: https://htmlpreview.github.io/?https://github.com/jiazhao97/Portal-reproducibility/blob/main/Reproduce-PBMC-ATACseq.html, with no deviation except for the input. Since cells from RNA and ATAC assays were concatenated, we expected same cells to overlap, but in the plot they didn't. 

We would appreciate your insight!

Thank you,
Yuying

**Comment by jiazhao97** [comment]
Hi Yuying,

Thank you for using Portal.

The default setting for integrating scRNA-seq and scATAC-seq is running Portal with `lambdacos=10.0`, as shown in the [tutorial](https://htmlpreview.github.io/?https://github.com/jiazhao97/Portal-reproducibility/blob/main/Reproduce-PBMC-ATACseq.html). Alternatively, you may try tuning parameter `lambdacos` ([link](https://github.com/YangLabHKUST/Portal#tuning-lambdacos-optional)) with the following code:

`adata_list = [adata_rna, adata_atac]`
`lowdim_list = portal.utils.preprocess_datasets(adata_list)`
`integrated_data = portal.utils.integrate_datasets(lowdim_list, search_cos=True)`

Sometimes, integration with tuning parameter `lambdacos` yields better result.

Also, you may try changing the number of highly variable genes.

Best,
Jia

**Comment by yuyingrong** [comment]
Hello Jia, 

Thank you for your suggestions! 

The optimal `lambdacos` calculated from `portal.utils.integrate_datasets` is 50.0. This `lambdacos` decreased overlap of same cells. 

`hvg_num` can be set as the third parameter in `model.preprocess(adata_rna, adata_atac, hvg_num=4000)` as described in [model.py](https://github.com/YangLabHKUST/Portal/blob/main/portal/model.py). Increasing `hvg_num` to 12000 increased the number of shared hvg between layers from 267 to 2797. More shared hvg improved cluster separation but decreased overlap of same cells. 

Setting `lambdacos=50.0` and `hvg_num=12000` simultaneously resulted in the least overlap. 

It seems that optimizing `lambdacos` and `hvg_num` revealed more distinction between sequencing methods than improved integration of same-cells. 

![portal_nPC30_nLatent20_hvg4000_l1](https://user-images.githubusercontent.com/50842845/228563441-48d393a9-88cb-4121-b2c3-a5fc0ecdfa4f.png)
⬆️ nPC30_nLatent20_lamdacos10_hvg4000 ([tutorial](https://htmlpreview.github.io/?https://github.com/jiazhao97/Portal-reproducibility/blob/main/Reproduce-PBMC-ATACseq.html) default)

![portal_nPC30_nLatent20_lamdacos50_hvg4000_l1](https://user-images.githubusercontent.com/50842845/228563485-5c985980-606f-4e6d-9abd-26fb410038e1.png)
⬆️ nPC30_nLatent20_lamdacos50_hvg4000

![portal_nPC30_nLatent20_hvg12000_l1](https://user-images.githubusercontent.com/50842845/228563503-bb048c0b-449e-44e0-899e-be04ba61b1fd.png)
⬆️ nPC30_nLatent20_lamdacos10_hvg12000

![portal_nPC30_nLatent20_lambdacos50_hvg12000_l1](https://user-images.githubusercontent.com/50842845/228563510-851528c0-556b-4d13-9a71-a358bb98e834.png)
⬆️ nPC30_nLatent20_lambdacos50_hvg12000

We speculated that optimizing `lambdacos` had the opposite effect, because our test multiome dataset has less cells (10k) than the multiome dataset (60k) used in the [benchmarking study](https://doi.org/10.3389/fmolb.2022.962644) that used Portal. What would be your insight on this? :)

Since our dataset is smaller, we tweaked the other two parameters of `portal.model.Model(npcs=30, n_latent=20, lambdacos=10.0,)`, described in [model.py](https://github.com/YangLabHKUST/Portal/blob/main/portal/model.py). At `npcs=20`, `n_latent=30`, and `hvg_num=12000`, we saw the best overlap. 

![portal_nPC15_nLatent10_hvg4000_l1](https://user-images.githubusercontent.com/50842845/228567632-84886c6f-bfbd-4622-b4f2-0599b0889aed.png)
⬆️ nPC15_nLatent10_lamdacos10_hvg4000

![portal_nPC15_nLatent20_hvg4000_l1](https://user-images.githubusercontent.com/50842845/228567639-07550666-5130-4816-b0a2-8081a2288e87.png)
⬆️ nPC15_nLatent20_lamdacos10_hvg4000

![portal_nPC15_nLatent30_hvg4000_l1](https://user-images.githubusercontent.com/50842845/228567644-a6da25ba-a241-4d53-b5fd-11a8980a0b72.png)
⬆️ nPC15_nLatent30_lamdacos10_hvg4000

![portal_nPC20_nLatent10_hvg4000_l1](https://user-images.githubusercontent.com/50842845/228567651-5bdef72d-0a51-45f7-ba9b-eae3b6b2acf9.png)
⬆️ nPC20_nLatent10_lamdacos10_hvg4000

![portal_nPC20_nLatent20_hvg4000_l1](https://user-images.githubusercontent.com/50842845/228567653-9e4d982a-aefb-4b47-bfc6-3e09a66a86f4.png)
⬆️ nPC20_nLatent20_lamdacos10_hvg4000

![portal_nPC20_nLatent30_hvg4000_l1](https://user-images.githubusercontent.com/50842845/228567655-ffd87b2e-3022-4c24-9d26-5502f7e25ad5.png)
⬆️ nPC20_nLatent30_lamdacos10_hvg4000

More hvg: 
![portal_nPC15_nLatent10_hvg12000_l1](https://user-images.githubusercontent.com/50842845/228568076-2d585229-682e-490b-acfc-bc731b7fc0db.png)
⬆️ nPC15_nLatent10_lamdacos10_hvg12000

![portal_nPC15_nLatent20_hvg12000_l1](https://user-images.githubusercontent.com/50842845/228568087-44afa2cb-3d11-4711-9f2c-8619f69ceb73.png)
⬆️ nPC15_nLatent20_lamdacos10_hvg12000

![portal_nPC15_nLatent30_hvg12000_l1](https://user-images.githubusercontent.com/50842845/228568092-578bafbc-27e8-476e-a0cb-87ddc5701b73.png)
⬆️ nPC15_nLatent30_lamdacos10_hvg12000

![portal_nPC20_nLatent10_hvg12000_l1](https://user-images.githubusercontent.com/50842845/228568096-d876300c-0fa9-4fbc-81c6-4bb02188243c.png)
⬆️ nPC20_nLatent10_lamdacos10_hvg12000

![portal_nPC20_nLatent20_hvg12000_l1](https://user-images.githubusercontent.com/50842845/228568100-ebe79713-50fe-4b3f-b09e-0823a85416c1.png)
⬆️ nPC20_nLatent20_lamdacos10_hvg12000

![portal_nPC20_nLatent30_hvg12000_l1](https://user-images.githubusercontent.com/50842845/228568107-89967fbb-ad17-4090-8798-5f2701d4d0b4.png)
⬆️ **nPC20_nLatent30_lamdacos10_hvg12000 (best)**

![portal_nPC20_nLatent40_hvg12000_l1](https://user-images.githubusercontent.com/50842845/228568109-30011ddd-27e3-47ba-bf06-6f5401afa840.png)
⬆️ nPC20_nLatent40_lamdacos10_hvg12000

![portal_nPC30_nLatent30_hvg12000_l1](https://user-images.githubusercontent.com/50842845/228568111-9d58ad3d-235d-4e6e-8fbf-b80ad3808512.png)
⬆️ nPC30_nLatent30_lamdacos10_hvg12000

![portal_nPC20_nLatent30_lambda50_hvg12000_l1](https://user-images.githubusercontent.com/50842845/228578053-272b2e7f-760d-4efc-8ce0-01bfae7ef63c.png)
⬆️ nPC20_nLatent30_lambda50_hvg12000
