### ISSUE TITLE
conda version to install portal

### ISSUE THREAD

**Issue by JianiC** [YangLabHKUST/Portal#9]
Hi, I am interested in portal package and I have tried to install both via pip and manual install with git:
In order to install torch==1.8.1, I have to use conda < 2021
 when I tried pip

<img width="1068" alt="Screenshot 2024-07-07 at 5 22 55 PM" src="https://github.com/YangLabHKUST/Portal/assets/47227610/92719e3c-a4f3-44c4-95f5-6fe3d70a720b">

I also tried a old version of conda and I can install rpy2 but having issue with igraph
<img width="1067" alt="Screenshot 2024-07-07 at 5 24 16 PM" src="https://github.com/YangLabHKUST/Portal/assets/47227610/0
<img width="1081" alt="Screenshot 2024-07-07 at 5 24 32 PM" src="https://github.com/YangLabHKUST/Portal/assets/47227610/31769c65-905c-49ff-8762-19c316453a3b">

I have also tried manual install via conda
`conda env update --f environment.yml` but I faced other conflicts
<img width="1073" alt="Screenshot 2024-07-07 at 5 26 15 PM" src="https://github.com/YangLabHKUST/Portal/assets/47227610/cc58fa17-fb89-447a-a096-15b520b6240b">

Do you have any suggestion to install portal package?  Thank you!

**Comment by gefeiwang** [comment]
Hi,

We have removed the dependency on rpy2 and some other packages that may cause dependency error on pypi. You can try to install the new package with `pip install portal-sc==1.0.4`.

Best,
Gefei

**Comment by JianiC** [comment]
> Hi,
> 
> We have removed the dependency on rpy2 and some other packages that may cause dependency error on pypi. You can try to install the new package with `pip install portal-sc==1.0.4`.
> 
> Best, Gefei

Thank you for  the prompt response and working on that! Changing the portal to a new version did solve the install error, but I faced a new problem when I import scanpy
<img width="1157" alt="Screenshot 2024-07-10 at 9 35 01 AM" src="https://github.com/YangLabHKUST/Portal/assets/47227610/b1f93a5f-59a0-4ce0-902e-cd9ce4ab8d12">

I finally work around the problem after I change the pytorch version to 1.9 in the yml file.
